---
- name: test
  hosts: all
  become: true
  tasks:
    - name: httpd remove
      yum:
        name: httpd
        state: absent
        
    - name: httpd reinstall
      yum:
        name: httpd
        state: present
        
    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
        
    - name: start httpd
      service:
        name: httpd
        state: restarted
        enabled: true
